apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: index.docker.io/strongmonkey1992/test-scan:v1.0.2 # {"$imagescan": "fleet-local:test-scan"}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
      - name: slave-1
        image: index.docker.io/strongmonkey1992/test-scan-1:v1.0.3 # {"$imagescan": "fleet-local:test-scan-1"}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
